version: "1.0"

services:
  web:
    container_name: tomcat
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - DB

  DB:
    image: postgres:16.4
    ports:
      - "5432:5432"
    container_name: postgresql
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./DB:/var/lib/postgresql/data
      - ./ddl/user.sql:/docker-entrypoint-initdb.d/user.sql
    restart: always